apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-stream-output-2
  labels:
    app: pubsub-stream-output-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-stream-output-2
  template:
    metadata:
      labels:
        app: pubsub-stream-output-2
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
      containers:
      - name: pubsub-stream-output-2
        image: tiencheng/pubsub-stream-output:1.3
        resources:
          limits:
            cpu: "2.0"
            memory: "4Gi"
          requests:
            cpu: "1.0"
            memory: "2Gi"
        # Add the following env section
        env:
        - name: BROKER
          value: kafka
        - name: KAFKA_CONSUMER_GROUP
          value: out2
        - name: KAFKA_CONSUME_TOPIC
          value: tracks2
        envFrom:
          - configMapRef:
              name: kafka-common
          - configMapRef:
              name: component-common
          - configMapRef:
              name: non-triton
          - configMapRef:
              name: redis-common
        volumeMounts:
          - mountPath: /data
            name: data-volume