apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-volume
spec:
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
