apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-detector-1
  labels:
    app: pubsub-detector-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-detector-1
  template:
    metadata:
      labels:
        app: pubsub-detector-1
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
      containers:
      - name: pubsub-detector-1
        image: tiencheng/pubsub-detector:1.0
        resources:
          limits:
            cpu: "4.0"
            memory: "8Gi"
          requests:
            cpu: "1.0"
            memory: "4Gi"
        # Add the following env section
        env:
        - name: BROKER
          value: kafka
        - name: KAFKA_CONSUMER_GROUP
          value: dets
        - name: KAFKA_CONSUME_TOPIC
          value: frames
        - name: KAFKA_PRODUCE_TOPIC
          value: dets
        envFrom:
          - configMapRef:
              name: kafka-common
          - configMapRef:
              name: component-common
          - configMapRef:
              name: non-triton
        volumeMounts:
          - mountPath: /data
            name: data-volume