apiVersion: v1
data:
  JINA_LOG_LEVEL: INFO
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: gateway-configmap
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  ports:
  - name: port
    port: 4091
    protocol: TCP
    targetPort: 4091
  selector:
    app: gateway
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: gateway
        jina_deployment_name: gateway
        ns: default
        pod_type: GATEWAY
        shard_id: ''
    spec:
      containers:
      - args:
        - gateway
        - --extra-search-paths
        - ''
        - --k8s-namespace
        - default
        - --prefetch
        - '5'
        - --expose-endpoints
        - '{}'
        - --uses
        - GRPCGateway
        - --graph-description
        - '{"Detector": ["Tracker1", "Tracker2", "Tracker3"], "start-gateway": ["Detector"],
          "Tracker1": ["Output1"], "Tracker2": ["Output2"], "Tracker3": ["SaveFrame",
          "Output3"], "SaveFrame": [], "Output1": [], "Output2": [], "Output3": ["end-gateway"]}'
        - --graph-conditions
        - '{"Tracker1": {"tags__output_stream": {"$eq": 1}}, "Tracker2": {"tags__output_stream":
          {"$eq": 2}}, "Tracker3": {"tags__output_stream": {"$eq": 3}}, "Output1":
          {"tags__output_stream": {"$eq": 1}}, "Output2": {"tags__output_stream":
          {"$eq": 2}}, "Output3": {"tags__output_stream": {"$eq": 3}}}'
        - --deployments-addresses
        - '{"Detector": ["grpc://detector.default.svc:8080"], "Tracker1": ["grpc://tracker1.default.svc:8080"],
          "Tracker2": ["grpc://tracker2.default.svc:8080"], "Tracker3": ["grpc://tracker3.default.svc:8080"],
          "SaveFrame": ["grpc://saveframe.default.svc:8080"], "Output1": ["grpc://output1.default.svc:8080"],
          "Output2": ["grpc://output2.default.svc:8080"], "Output3": ["grpc://output3.default.svc:8080"]}'
        - --port
        - '4091'
        - --port-monitoring
        - '50246'
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: gateway
        - name: K8S_DEPLOYMENT_NAME
          value: gateway
        - name: K8S_NAMESPACE_NAME
          value: default
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: gateway-configmap
        image: jinaai/jina:3.12.0-py38-standard
        imagePullPolicy: IfNotPresent
        name: gateway
        ports:
        - containerPort: 4091
        readinessProbe:
          exec:
            command:
            - jina
            - ping
            - gateway
            - grpc://127.0.0.1:4091
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
