version: '3'

services:
  pubsub-detector:
    image: pubsub-detector:1.1
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  pubsub-save-frames:
    image: pubsub-save-frames:1.1
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  pubsub-stream-output:
    image: pubsub-stream-output:1.1
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  pubsub-tracker:
    image: pubsub-tracker:1.1
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]