version: '3'

services:
  pubsub-detector:
    image: pubsub-detector:1.2
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD/client/data:/data
  pubsub-save-frames:
    image: pubsub-save-frames:1.2
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD/client/data:/data
  pubsub-stream-output:
    image: pubsub-stream-output:1.2
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD/client/data:/data
  pubsub-tracker:
    image: pubsub-tracker:1.2
    network_mode: "host"        
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - $PWD/client/data:/data