apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-stream-output-1
  labels:
    app: pubsub-stream-output-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub-stream-output-1
  template:
    metadata:
      labels:
        app: pubsub-stream-output-1
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
      containers:
      - name: pubsub-stream-output-1
        image: tiencheng/pubsub-stream-output:1.3
        resources:
          limits:
            cpu: "4.0"
            memory: "4Gi"
          requests:
            cpu: "4.0"
            memory: "4Gi"
        # Add the following env section
        env:
        - name: BROKER
          value: zmq
        - name: ZMQ_HOSTNAME
          value: "*"
        - name: ZMQ_PORT_IN
          value: "1113"
        envFrom:
          - configMapRef:
              name: kafka-common
          - configMapRef:
              name: component-common
          - configMapRef:
              name: non-triton
          - configMapRef:
              name: redis-common
        volumeMounts:
          - mountPath: /data
            name: data-volume