apiVersion: v1
data:
  JINA_LOG_LEVEL: INFO
  pythonunbuffered: '1'
  worker_class: uvicorn.workers.UvicornH11Worker
kind: ConfigMap
metadata:
  name: deepsort-configmap
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deepsort
  name: deepsort
  namespace: default
spec:
  ports:
  - name: port
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: deepsort
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepsort
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepsort
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: deepsort
        jina_deployment_name: DeepSORT
        ns: default
        pod_type: WORKER
        shard_id: '0'
    spec:
      containers:
      - args:
        - executor
        - --name
        - DeepSORT
        - --extra-search-paths
        - ''
        - --k8s-namespace
        - default
        - --uses
        - config.yml
        - --port
        - '8080'
        - --port-monitoring
        - '9090'
        - --uses-metas
        - '{}'
        - --uses-with
        - '{"embedder_kwargs": {"embedder": "$TRACKER_EMBEDDER", "embedder_model_name":
          "$TRACKER_EMBEDDER_MODEL_NAME", "embedder_model_version": "$TRACKER_EMBEDDER_MODEL_VERSION",
          "triton_url": "$TRACKER_TRITON_URL"}}'
        - --native
        command:
        - jina
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: JINA_DEPLOYMENT_NAME
          value: DeepSORT
        - name: K8S_DEPLOYMENT_NAME
          value: deepsort
        - name: K8S_NAMESPACE_NAME
          value: default
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - configMapRef:
            name: deepsort-configmap
        image: jina-tracker:1.0
        imagePullPolicy: IfNotPresent
        name: executor
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - jina
            - ping
            - executor
            - 127.0.0.1:8080
          initialDelaySeconds: 5
          periodSeconds: 20
          timeoutSeconds: 10
