apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
      containers:
      - name: client
        image: tiencheng/test-client:1.5 # test-client:1.5
        ports:
        - containerPort: 80
        command: ["sleep"]
        args: ["infinity"]
        resources:
          limits:
            cpu: "8.0"
            memory: "16Gi"
          requests:
            cpu: "4.0"
            memory: "16Gi"
        envFrom:
          - configMapRef:
              name: kafka-common
          - configMapRef:
              name: component-common
          - configMapRef:
              name: non-triton
          - configMapRef:
              name: redis-common
        volumeMounts:
        - name: data-volume
          mountPath: /data